"""empty message

Revision ID: 2c37313e24e0
Revises: ea274abf04b0
Create Date: 2021-04-13 04:30:08.195613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c37313e24e0'
down_revision = 'ea274abf04b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('password', sa.String(length=255), nullable=False))
    op.alter_column('account', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('account', 'course',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
               nullable=False)
    op.alter_column('account', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=True)
    op.alter_column('account', 'course',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
               nullable=True)
    op.alter_column('account', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('account', 'password')
    # ### end Alembic commands ###
